### ISSUE TITLE
question about parsing

### ISSUE THREAD

**Issue by tischi** [ssgpers/java-utils--embl-cba#2]
input: 

```
B4--W00016--P00004--Z00023--T00000--Trans.tif
```
output:

```
masterRegExp="(?<treatment>.+)--W(?<well>\\d+)--P(?<position>\\d+)--Z(?<slice>\\d+)--T(?<timePoint>\\d+)--(?<channel>.+)\\.tif"

B4--W00016--P00004--Z(?<slice>\d+)--T(?<timePoint>\d+)--(?<channel>.+)\.tif
```

This looks fine but I do not understand the last `\.tif`.
What is it supposed to mean?

**Comment by ssgpers** [comment]
Dot in regular expressions has a special meaning (any symbol). To encode dot (.) as a symbol one needs to put \ before
